#!/usr/bin/env ruby

require 'getoptlong'
require_relative "core/assembler"

if ARGV.length < 1
  puts <<-EOF
    Usage: ./assemble filenames... [--binary, -b] [--no-metada, -n] [--start-point, -s filename] [--tail-padding, -t tail filename] 
  EOF
  exit
end

start_point = nil
tail_padding = nil
output_format = :ascii_with_metadata

GetoptLong.new(
  ['--start-point', '-s', GetoptLong::REQUIRED_ARGUMENT],
  ['--tail-padding', '-t', GetoptLong::REQUIRED_ARGUMENT],
  ['--binary', '-b', GetoptLong::NO_ARGUMENT],
  ['--no-metadata', '-n', GetoptLong::NO_ARGUMENT]
).each do |opt, arg|
  case opt
  when '--start-point'
    start_point = arg
  when '--tail-padding'
    tail_padding = arg
  when '--binary'
    output_format = :binary
  when '--no-metadata'
    output_format = :ascii
  end
end

ARGV.unshift start_point if start_point
ARGV.push tail_padding if tail_padding

as = Assembler.new
print as.assemble(ARGV)[output_format]
