#!/usr/bin/env ruby

require 'getoptlong'
require_relative "core/assembler"

def help
  puts <<-EOF
Usage: ./assemble filenames...
  --binary -b               Output the raw binary assembled data 
  --ascii-with-metadata -m  (default) Output the assembled data in ASCII string with metadata
  --ascii -a                Output the assembled data in ASCII string
  EOF
end

if ARGV.length < 1
  help
  exit
end

start_point = nil
tail_padding = nil
output_format = :ascii_with_metadata

GetoptLong.new(
  ['--binary', '-b', GetoptLong::NO_ARGUMENT],
  ['--ascii-with-metadata', '-m', GetoptLong::NO_ARGUMENT],
  ['--ascii', '-a', GetoptLong::NO_ARGUMENT],
  ['--help', '-h', GetoptLong::NO_ARGUMENT]
).each do |opt, arg|
  case opt
  when '--help'
    help
    exit
  when '--binary'
    output_format = :binary
  when '--ascii-with-metadata'
    output_format = :ascii_with_metadata
  when '--ascii'
    output_format = :ascii
  end
end

ARGV.unshift start_point if start_point
ARGV.push tail_padding if tail_padding

as = Assembler.new
print as.assemble(ARGV)[output_format]
